[metadata]
name = "EyeMath"
version = "0.0.1"

[paths]
base_dir = "/home/usov/myprojects/EyeMath/"
res_dir = "/home/usov/myprojects/EyeMath/res/"
data_dir = "/home/usov/myprojects/EyeMath/data/"
go_dir = "/home/usov/myprojects/EyeMath/res/go/"
binary_dir = "/home/usov/myprojects/EyeMath/res/go/binary/"
compiler = "/snap/bin/go"

[go]
go_build_flags = "build -o"
check_path_go_cmd = "which go"
go_file = "_Server_.go"
compiled_file = "_Server_"

[MaL]
PRECISION = 32
DEFAULT_PREC = 48
