version: '3.9'


x-env: &env_vars
  TZ: ${SYSTEM_TIME_ZONE}
  RUNNING_INSIDE_DOCKER: 1
  GATEWAY_HOST: ${GATEWAY_HOST}
  GATEWAY_APP_PORT: ${GATEWAY_APP_PORT}
  GATEWAY_GRPC_HOST: ${GATEWAY_GRPC_HOST}
  GATEWAY_GRPC_APP_PORT: ${GATEWAY_GRPC_APP_PORT}
  RECOGNIZER_HOST: ${RECOGNIZER_HOST}
  RECOGNIZER_APP_PORT: ${RECOGNIZER_APP_PORT}
  RENDERER_HOST: ${RENDERER_HOST}
  RENDERER_APP_PORT: ${RENDERER_APP_PORT}
  SOLVER_HOST: ${SOLVER_HOST}
  SOLVER_APP_PORT: ${SOLVER_APP_PORT}


services:
  gateway:
    build: gateway
    container_name: gateway
    environment: *env_vars
    ports:
      - "${GATEWAY_APP_PORT}:${GATEWAY_APP_PORT}"
    networks:
      - eye_math_network
    restart: ${DOCKER_CONTAINERS_RESTART}


  recognizer:
    build: recognizer
    container_name: recognizer
    environment: *env_vars
    ports:
      - "${RECOGNIZER_APP_PORT}:${RECOGNIZER_APP_PORT}"
    networks:
      - eye_math_network
    restart: ${DOCKER_CONTAINERS_RESTART}


  renderer:
    build: renderer
    container_name: renderer
    environment: *env_vars
    ports:
      - "${RENDERER_APP_PORT}:${RENDERER_APP_PORT}"
    networks:
      - eye_math_network
    restart: ${DOCKER_CONTAINERS_RESTART}


  solver:
    build: solver
    container_name: solver
    environment: *env_vars
    ports:
      - "${SOLVER_APP_PORT}:${SOLVER_APP_PORT}"
    networks:
      - eye_math_network
    restart: ${DOCKER_CONTAINERS_RESTART}

  

  # postgres:
  #   image: postgres:14
  #   environment:
  #     TZ: ${SYSTEM_TIME_ZONE}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB_NAME}
  #   ports:
  #     - ${POSTGRES_PORT}
  #   networks:
  #     - eye_math_network
  #   # volumes:
  #   #   - postgres_data:/var/lib/postgresql/data
  #   restart: ${DOCKER_CONTAINERS_RESTART}

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     TZ: ${SYSTEM_TIME_ZONE}
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #   ports:
  #     - ${PGADMIN_PORT}
  #   networks:
  #     - eye_math_network
  #   restart: ${DOCKER_CONTAINERS_RESTART}
  #   volumes:
  #     - pgadmin_data:/var/lib/pgadmin

  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   restart: on-failure


volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  eye_math_network:
    driver: bridge
    name: eye_math_network