version: '3.9'

services:
  api_gateway:
    build: ./API_GATEWAY
    environment:
      - HOST=${API_GATEWAY_HOST}
      - PORT=${API_GATEWAY_APP_PORT}
    ports:
      - ${API_GATEWAY_PORT}
    volumes:
      - ./API_GATEWAY:/app
    restart: on-failure  

  math_solve:
    build: ./MATH_SOLVE 
    environment:
      - HOST=${MATH_SOLVE_HOST}
      - PORT=${MATH_SOLVE_APP_PORT}
    ports:
      - ${MATH_SOLVE_PORT}
    volumes:
      - ./MATH_SOLVE:/code
    restart: on-failure

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: on-failure

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure

volumes:
  postgres_data:
    driver: local