FROM python:3.13.5-slim
# Here we using ubuntu because alpine is not supported by pytorch
# wheels only for manylinux_2_28_x86_64 / aarch64 / mac / win


RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    bash \
    git \
    curl \
    ca-certificates \
    tzdata \
  && update-ca-certificates \
  && rm -rf /var/lib/apt/lists/*


RUN adduser --disabled-password --gecos "" appuser && \
    mkdir -p /app/gen && \
    chown -R appuser:appuser /app


RUN curl -fsSL https://astral.sh/uv/install.sh -o /tmp/uv-installer.sh
RUN sh /tmp/uv-installer.sh ~/.local/bin \
    && rm /tmp/uv-installer.sh


RUN mv /root/.local/bin/uv /usr/local/bin/uv \
    && mv /root/.local/bin/uvx /usr/local/bin/uvx \
    && chmod +x /usr/local/bin/uv /usr/local/bin/uvx
ENV PATH="/usr/local/bin:${PATH}"


COPY . /app
WORKDIR /app


RUN chown -R appuser:appuser /app
RUN chmod -R a+rx /usr/local/bin


RUN uv sync && chown -R appuser:appuser /app


EXPOSE ${PORT}
USER appuser
ENTRYPOINT ["./entrypoint.sh"]


