# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service_math_solve.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service_math_solve.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18service_math_solve.proto\x12\tmathsolve\"\"\n\x0cSolveRequest\x12\x12\n\nexpression\x18\x01 \x01(\t\"\x80\x01\n\rSolveResponse\x12/\n\x06status\x18\x01 \x01(\x0e\x32\x1f.mathsolve.SolveResponse.Status\x12\x0e\n\x06result\x18\x02 \x01(\t\x12\x11\n\terror_msg\x18\x03 \x01(\t\"\x1b\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x32H\n\nMathSolver\x12:\n\x05Solve\x12\x17.mathsolve.SolveRequest\x1a\x18.mathsolve.SolveResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_math_solve_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SOLVEREQUEST']._serialized_start=39
  _globals['_SOLVEREQUEST']._serialized_end=73
  _globals['_SOLVERESPONSE']._serialized_start=76
  _globals['_SOLVERESPONSE']._serialized_end=204
  _globals['_SOLVERESPONSE_STATUS']._serialized_start=177
  _globals['_SOLVERESPONSE_STATUS']._serialized_end=204
  _globals['_MATHSOLVER']._serialized_start=206
  _globals['_MATHSOLVER']._serialized_end=278
# @@protoc_insertion_point(module_scope)
