FROM python:3.13.2-slim


RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      build-essential \
      protobuf-compiler \
      git \
      curl \
      ca-certificates && \
    rm -rf /var/lib/apt/lists/*

# Creating of appuser and group.
RUN useradd -m appuser && \
    mkdir -p /app/gen && \
    chown -R appuser:appuser /app

RUN curl -fsSL https://astral.sh/uv/install.sh -o /tmp/uv-installer.sh
RUN sh /tmp/uv-installer.sh ~/.local/bin \
    && rm /tmp/uv-installer.sh

# Copying uv binary from ~/.local/bin to /usr/local/bin
RUN cp /root/.local/bin/uv /usr/local/bin/uv \
    && cp /root/.local/bin/uvx /usr/local/bin/uvx \
    && chmod +x /usr/local/bin/uv /usr/local/bin/uvx
ENV PATH="/usr/local/bin:${PATH}"

# Using uv installing reqs to generate stubs.
RUN $UV pip install --no-cache-dir grpcio-tools grpcio-reflection

# Copying everything (except .dockerignore files) to /app directory.
COPY . /app
WORKDIR /app

# Apply appuser's previlegies for /app directory and for binary directory.
RUN chown -R appuser:appuser /app
RUN chmod -R a+rx /usr/local/bin

EXPOSE ${PORT}
USER appuser
CMD ["sh", "-c", "uv sync && uv run setup.py"]