apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 9999
      targetPort: 9999
      nodePort: 30080


---


apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - name: port-8080
      port: 8080
      targetPort: 8080
      nodePort: 30081

    - name: port-8081
      port: 8081
      targetPort: 8081
      nodePort: 30082 