apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 9999
      resources:
        limits:
          memory: "256Mi"
          cpu: "250m"


---


apiVersion: v1
kind: Pod
metadata:
  name: gateway-pod
  labels:
    app: gateway
spec:
  containers:
    - name: gateway
      image: gateway:latest
      ports:
        - containerPort: 8080
        - containerPort: 8081
      resources:
        limits:
          memory: "256Mi"
          cpu: "250m"