apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    components: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 9999
      resources:
        limits:
          memory: "256Mi"
          cpu: "250m"
      