FROM postgres:14


RUN apt-get update && apt-get install -y gettext-base && apt-get clean

RUN mkdir -p /init-scripts && chown postgres:postgres /init-scripts && chmod 777 /init-scripts

COPY init-scripts/ /init-scripts/

RUN chown postgres:postgres /init-scripts/* && \
    chmod +x /init-scripts/init-db.sh


COPY /init-scripts/entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]