FROM python:3.13.2-slim



RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      build-essential \
      protobuf-compiler \
      git \
      curl \
      ca-certificates && \
    rm -rf /var/lib/apt/lists/*

# Creating of appuser and group.
RUN useradd -m appuser && \
    mkdir -p /app/gen && \
    chown -R appuser:appuser /app

# Clonning .proto files from owr repo.
RUN git clone --depth=1 https://github.com/dagahan/EyeMath_protos.git /protos

# Installing UV and other reqs for python.
RUN pip install --no-cache-dir grpcio-tools grpcio-reflection && \
    pip install --no-cache-dir uv

# Generating stubs from cloned .proto files.
RUN find /protos -type f -name '*.proto' -exec python -m grpc_tools.protoc \
      -I /protos \
      --python_out=/app/gen \
      --grpc_python_out=/app/gen \
      --pyi_out=/app/gen \
      {} \;

# Copying everything (except .dockerignore files) to /app directory.
COPY . /app
WORKDIR /app

# Configure owr Python path.
ENV PATH="/usr/local/bin:$PATH" \
    PYTHONPATH="/app/gen:$PYTHONPATH"

# Apply appuser's previlegies for /app directory.
RUN chown -R appuser:appuser /app

# Executing Math Solve Service!
EXPOSE ${PORT}
USER appuser
CMD ["sh", "-c", "uv sync && uv run service_math_solve.py"]