# ----------------------------
# 1. Builder stage: ставим protoc, grpcio-tools, генерим stubs и ставим все зависимости
# ----------------------------

FROM python:3.11-slim-bookworm as builder

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      build-essential \
      protobuf-compiler \
      gcc && \
    rm -rf /var/lib/apt/lists/*


WORKDIR /app
COPY req.txt .
RUN pip install --user --no-cache-dir -r req.txt


COPY proto/service_math_solve.proto proto/service_math_solve.proto
RUN python -m grpc_tools.protoc \
      -I proto \
      --python_out=. \
      --grpc_python_out=. \
      proto/service_math_solve.proto


# Копируем остальной код
COPY service_math_solve.py service_math_solve.py
COPY service_math_config.toml service_math_config.toml
COPY proto/service_math_solve_pb2.py service_math_solve_pb2.py
COPY proto/service_math_solve_pb2_grpc.py service_math_solve_pb2_grpc.py





# ----------------------------
# 2. Runtime stage: только минимальный набор
# ----------------------------

FROM python:3.11-slim-bookworm


WORKDIR /app
# Берём из билдера установленные пакеты и stubs
COPY --from=builder /root/.local /root/.local
COPY --from=builder /app /app


ENV PATH=/root/.local/bin:$PATH
EXPOSE ${PORT}


CMD ["python", "-u", "service_math_solve.py"]