[project]
name = "service_mathsolve"
version = "0.0.1"
dependencies = [
    "fastapi==0.115.12",
    "latex2sympy2==1.9.1",
    "loguru==0.7.3",
    "mpmath==1.3.0",
    "pydantic==2.11.5",
    "sympy==1.14.0",
    "toml==0.10.2",
    "uvicorn==0.34.2",
    "grpcio-tools",
    "grpcio-reflection",
    "protofileseyemath@git+https://github.com/dagahan/EyeMath_protosPY"
]
LOGGING_REQUESTS = true
LOGGING_RESPONSES = false


[MaL]
PRECISION = 32
DEFAULT_PREC = 48


[host]
HOST = "0.0.0.0"    
PORT = 8001
reload = true


[proto]
PROTO_REPO_URL = 'https://github.com/dagahan/EyeMath_protos.git'
PROTO_REPO_BRANCH = 'master'
PROTO_PYTHON_PATH = 'py'