name: Python CI/CD Pipeline

on:
  push:
    branches: [ ci_cd ]
  pull_request:
    branches: [ ci_cd ]

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Docker
      uses: docker/setup-buildx-action@v2

    - name: Start services
      run: docker compose up --build -d

    - name: Wait for services
      run: |
        sleep 15
        docker compose ps

    - name: Run tests
      run: |
        # Пример теста для веб-сервиса
        curl -sSf http://localhost:8080/health
        # Или запуск тестов внутри контейнера
        docker compose exec -T service pytest

    - name: Stop services
      if: always()
      run: docker compose down